### ISSUE TITLE
Question about SimMetrics license

### ISSUE THREAD

**Issue by JonoYang** [mpkorstanje/simmetrics#16]
I had a question about the license of SimMetrics and how it was relicensed from GPL 2.0.

In this commit (https://github.com/mpkorstanje/simmetrics/commit/8307a58005425a06930c42f4a5400a3d0eaf403b), the license of the project has been changed from GPL 2.0 and several authors removed. I'd like to know the circumstances behind this change.

**Comment by mpkorstanje** [comment]
In the period of Dec 2014 to Jan 2016 I undertook a complete rewrite of Simmetrics. In this period the structure, organization, naming and tests have been effectively been redeveloped. The implementations of the algorithms have all been rewritten based on the sources linked in their documentation. Overall this effort was guide by a vision of a library that would be simple, correct, elegant, both in structure, organization and written code. And above all a joy to use.

While the project still bears the name of it's predecessor at that point in time I considered it a distinct work from the original Simmetrics and myself the sole author. I also considered the Apache 2.0 Licence to be a more practical licence for my work. Hence the change in licensing and the removal of other authors.

**Comment by JonoYang** [comment]
Thank you for clarifying!
