### ISSUE TITLE
maven-enforcer-plugin 3.0.0-M1

### ISSUE THREAD

**Issue by dennisfabri** [mpkorstanje/simmetrics#20]
I just checked the pom.xml and found this milestone version for the maven-enforcer-plugin. Is it really needed?

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-enforcer-plugin</artifactId>
  <version>3.0.0-M1</version>
</plugin>
```

**Comment by mpkorstanje** [comment]
I'm generally adverse to using milestone versions so I assume there was a good reason. However it has been so long ago I can really can't remember why I picked that version.
